# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 一条没有尽头的道路，我们乐在其中
email: xxoolltt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    曾经 : 单片机 - arm - FPGA - pcb - 焊板子<br>
    现在 : c++ - java  - Android <br>
    将来 : javaScript - python - 后端/全栈<br>
    我们的征途是星辰大海<br>
    
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xxoolltt.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: xxoolltt 

# Permalinks


# Set encoding to UTF-8
encoding: utf-8

collections:
  texts:
    output: true


    # Build settings
markdown: kramdown 
highlight: true 

redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables
